config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'groups#index'

  resources :groups, only: [:index, :show, :new, :create, :destroy]
  resources :payments, only: [:new, :create, :destroy]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :manage, Group, user_id: user.id
    can :manage, Payment, user_id: user.id
    can :read, :all
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :payments, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :payments

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups
  end

  def create
    group = current_user.groups.new(group_params)
    respond_to do |format|
      format.html do
        if group.save
          flash[:success] = 'Created New Group Succesfully!'
          redirect_to groups_path
        else
          render :new, alert: 'Error occured!'
        end
      end
    end
  end

  def new
    @group = Group.new
    @icons = { 'Grocery' => 'icon0.png', 'Food' => 'icon1.png', 'Bills' => 'icon2.jpg', 'Housing' => 'icon3.png',
               'Mortgage' => 'icon4.png', 'Shopping' => 'icon5.png' }
  end

  def show
    @group = Group.find(params[:id])
    @payments = @group.payments
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to groups_path
    flash[:success] = 'Group Deleted!'
  end

  private

  def group_params
    params.require(:data).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @group = Group.find(params[:id])
    @payment = Payment.new
  end

  def create
    @group = Group.find_by(name: payment_params[:category])
    payment = @group.payments.new(name: payment_params[:name], amount: payment_params[:amount],
                                  user_id: current_user.id, group_id: @group.id)
    respond_to do |format|
      format.html do
        if payment.save
          flash[:success] = 'New Payment Added Succesfully!'
          redirect_to group_path(@group.id)
        else
          render :new, alert: 'Error occured!'
        end
      end
    end
  end

  def destroy
    payment = Payment.find(params[:id])
    payment.destroy
    redirect_to root_path
    flash[:success] = 'Payment Deleted'
  end

  private

  def payment_params
    params.require(:data).permit(:name, :amount, :category)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/index.html.erb
<div class='back-arrow-cont d-flex a-cnter j-center'>
    <h1 class='repair-header d-flex a-center j-center'>All Categories</h1>
</div>
<%if @groups.empty?%>
  <div class='equipments-index-page d-flex a-center j-center'>
    <h1 class='index-header'>No category for this user. Please add a category <%= link_to "here", new_group_path%></h2>
  </div>
<%else%>
 <div class='equipments-container d-flex f-col a-center j-center'>
    <div class='new-equipment d-flex a-center'>
          <%= link_to "Add new Category", new_group_path %>
    </div>
  <div class='new-equipment-container d-flex f-col a-center j-center'>
  <% @groups.each do |group| %>
  <%= link_to group_path(group.id) do %>
   <div class='equipment d-flex a-center'>
     <%=image_tag "#{group.icon}" , width:'150px', height:'150px' %>
     <div class='name-date d-flex f-col a-center'>
       <p ><%= group.name %></p>
       <p> <%= group.created_at.strftime("%d-%b-%Y")%></p>
      </div>
 
    <p class='price'> $<%= group.payments.sum(:amount)%></p>
  
    <%if can? :destroy, group%>
        <%=button_to "Delete", group_path(group.id), method: :delete%>
      <%end%>

    </div>
  <%end%>
<%end%>
</div>
</div>
<%end%>

app/views/groups/new.html.erb
<div class='back-arrow-cont d-flex a-cnter j-center'>
    <h1 class='repair-header d-flex a-center j-center'>New Category</h1>
    <%= link_to root_path do %>
    <%= image_tag("backarrow.png", width:'50px', height:'50px') %>
    <%end%>
</div>
<div class='add-equipment d-flex f-col a-center j-center'> 
    <%=form_with url: groups_path, scope: :data do |f| %>
      <div class="field3 d-flex a-center j-center f-col" >
        <%= f.label :icon, 'Select Icon' %>
         <%= f.select :icon, options_for_select([
      ['Grocery', @icons["Grocery"]],
      ['Food' ,@icons["Food"]],
      ['Bills' ,@icons["Bills"]],
      ['Housing' ,@icons["Housing"]],
      ['Mortgage' ,@icons["Mortgage"]],
      ['Shopping' ,@icons["Shopping"]],
    ]),{ include_blank: "Select Icon"}, required: true , class:"form-select"%>
      </div>
      <div class="field3 d-flex a-center j-center f-col">
        <%= f.label :name, 'Name'  %>
        <%= f.text_field :name, :required=>true %>
      </div>
    <div class="action1 d-flex a-center f-col">
         <%= f.submit "Add Category"%>
    </div>
<% end %>
</div>

app/views/groups/show.html.erb
<div class='back-arrow-cont d-flex a-cnter j-center'>
    <h1 class='repair-header d-flex a-center j-center'>Category Payment</h1>
    <%= link_to root_path do %>
    <%= image_tag("backarrow.png", width:'50px', height:'50px') %>
<%end%>
</div>
<%if @group.payments.empty?%>
  <div class='equipments-show-page d-flex a-center j-center'>
    <h1 class='index-header'>No payment for this category. Please add a payment <%= link_to "here", new_payment_path(id: @group.id)%></h2>
  </div>
<%else%>
    <div class='repair-cont d-flex f-col a-center j-center'>
    <%= render partial: "layouts/flash" %>
    <div class='equipment d-flex a-center'>
      <%= image_tag @group.icon, width:'150px', height:'150px' %>
            <div class='name-date d-flex f-col a-center'>
                <p><%= @group.name%></p>
                <p><%= @group.created_at.strftime('%d %b %Y at %I %M %p') %></p>
            </div>
            <h3 class='price'><%= "$#{@group.payments.sum(:amount)}"%></h3>
    </div>
    <div class='new-repair new-equipment d-flex a-center j-center'>
        <%= link_to "Add new Payment", new_payment_path(id: @group.id) %>
    </div>
    <div class='equip-repair-cont d-flex a-center j-center f-col'>
      <%@group.payments.order(created_at:'DESC').each do |pay|%>
        <div class='repair d-flex a-center'>
        <div class='cost-date d-flex f-col'>
           <h1><%= "Your #{pay.name } costs: $#{pay.amount} "%></h1>
            <p><%= pay.created_at.strftime("%d-%b-%Y") %></p>
        </div>
           
            <%if can? :destroy, pay %>
              <%= button_to "Delete", payment_path(id: pay.id), :method => :delete %>
            <%end%>
        </div>
    <%end%>
    </div>
    
   </div>
<%end%>

app/views/layouts/_flash.html.erb
<div class="flash d-flex a-center j-center">
    <% flash.each do |name, msg| %>
      <p class=<%= name %>><%= msg %> </p>
    <% end %>
</div>

app/views/layouts/_header.html.erb
<%if user_signed_in? %>
  <nav class ='nav d-flex a-center'>
  <%= link_to root_path do %>
    <div class='img-header d-flex a-center'>
    <%# <%= image_tag("hamburger.png", width:'50px', height:'50px') %>
    <h1 class='nav-header'>Budget Tracker</h1>
    </div>
  <%end%>
   <div class='link-cont d-flex a-center'>
     <div class='nav-links d-flex a-center'>
       <h3><%= "Logged in: #{current_user.name} " %> </h3>
       <%= link_to "View Categories", groups_path %>
       <%= link_to "Add a Category", new_group_path %>
       <%# <%= link_to "Add a Payment", new_payment_path %>
       <%= button_to "Logout", destroy_user_session_path, :method => :delete %>
     </div>
     
   </div>
  
  </nav>
  <%else%>
    <nav class ='nav d-flex a-center'>
       <h1 class='class-header'>Budget Tracker</h1>
    </nav>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
     <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=PT+Serif&family=Raleway:wght@300;700&family=Source+Sans+Pro:wght@300&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/payments/new.html.erb
<div class='back-arrow-cont d-flex a-cnter j-center'>
    <h1 class='repair-header d-flex a-center j-center'>Add Payment</h1>
     <%= link_to root_path do %>
       <%= image_tag("backarrow.png", width:'50px', height:'50px') %>
     <%end%>
</div>
<div class= 'add-equipment add-repair d-flex f-col a-center j-center'> 
    <%=form_with url: payments_path, scope: :data do |f| %>
      <div class="field3 d-flex a-center j-center f-col" >
        <%= f.label :category, 'Category'  %>
        <%=f.text_field :category, value: "#{@group.name}", class:"p-2 form-control", :readonly => true %>
      </div>
      <div class="field3 d-flex a-center j-center f-col">
        <%= f.label :name, 'Name'  %>
        <%= f.text_field :name, :required=>true %>
      </div>
       <div class="field3 d-flex a-center j-center f-col">
        <%= f.label :amount, 'Amount'  %>
        <%= f.number_field :amount, :min => '1', :required=>true %>
      </div>
    <div class="action1 d-flex a-center f-col">
         <%= f.submit "Add Payment"%>
    </div>
      
<% end %>
</div>